name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [ '8', '10', '12' ]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run format
      - run: npm run lint
